const PAGES = {
  HOME: 'HOME',
  ADDRESSES: 'ADDRESSES',
  ESTABLISHMENTS: 'ESTABLISHMENTS',
  CADASTRAL_OBJECTS: 'CADASTRAL_OBJECTS',
  PANORAMA: 'PANORAMA',

  DATASETS: 'DATASETS',
  DATASET_DETAIL: 'DATASET_DETAIL',
  SEARCH_DATASETS: 'SEARCH_DATASETS',

  DATA: 'DATA',
  DATA_QUERY_SEARCH: 'DATA_QUERY_SEARCH',
  DATA_GEO_SEARCH: 'DATA_GEO_SEARCH',
  DATA_SEARCH_CATEGORY: 'SEARCH_DATA_CATEGORY',
  DATA_DETAIL: 'DATA_DETAIL',

  CONSTRUCTION_FILE: 'CONSTRUCTION_FILE',

  // cms pages
  ARTICLES: 'ARTICLES',
  ARTICLE_DETAIL: 'ARTICLE_DETAIL',
  SEARCH_ARTICLES: 'SEARCH_ARTICLES',
  SPECIALS: 'SPECIALS',
  SPECIAL_DETAIL: 'SPECIAL_DETAIL',
  PUBLICATIONS: 'PUBLICATIONS',
  PUBLICATION_DETAIL: 'PUBLICATION_DETAIL',
  SEARCH_PUBLICATIONS: 'SEARCH_PUBLICATIONS',

  // text pages
  NEWS: 'NEWS',
  PROCLAIMER: 'PROCLAIMER',
  ACTUALITY: 'ACTUALITY',
  HELP: 'HELP',
  CONTROLS: 'CONTROLS',
  DATA_INFO: 'DATA_INFO',
  ABOUT_API: 'ABOUT_API',
  LOGIN: 'LOGIN',
  PRIVACY_SECURITY: 'PRIVACY_SECURITY',
  AVAILABILITY_QUALITY: 'AVAILABILITY_QUALITY',
  MANAGEMENT: 'MANAGEMENT',
  STATISTICS: 'STATISTICS',
  MOVED: 'MOVED',
  NOT_FOUND: 'NOT_FOUND',
}

export default PAGES

export const isOldCmsPage = page =>
  page === PAGES.NEWS ||
  page === PAGES.HELP ||
  page === PAGES.ACTUALITEIT ||
  page === PAGES.PROCLAIMER ||
  page === PAGES.CONTROLS ||
  page === PAGES.CONTROLS ||
  page === PAGES.DATA_INFO ||
  page === PAGES.ABOUT_API ||
  page === PAGES.PRIVACY_SECURITY ||
  page === PAGES.AVAILABILITY_QUALITY ||
  page === PAGES.STATISTICS ||
  page === PAGES.LOGIN ||
  page === PAGES.MOVED ||
  page === PAGES.NOT_FOUND ||
  page === PAGES.MANAGEMENT

export const isEditorialDetailPage = page =>
  page === PAGES.ARTICLE_DETAIL ||
  page === PAGES.PUBLICATION_DETAIL ||
  page === PAGES.SPECIAL_DETAIL

export const isEditorialOverviewPage = page =>
  page === PAGES.ARTICLES || page === PAGES.PUBLICATIONS || page === PAGES.SPECIALS

export const isEditorialPage = page => isEditorialDetailPage(page) || isEditorialOverviewPage(page)

export const isMapSplitPage = page =>
  page === PAGES.DATA ||
  page === PAGES.PANORAMA ||
  page === PAGES.DATA_DETAIL ||
  page === PAGES.ADDRESSES ||
  page === PAGES.ESTABLISHMENTS ||
  page === PAGES.DATA_GEO_SEARCH ||
  page === PAGES.CADASTRAL_OBJECTS

export const isQuerySearchPage = page =>
  page === PAGES.DATA_QUERY_SEARCH ||
  page === PAGES.SEARCH_DATASETS ||
  page === PAGES.SEARCH_ARTICLES ||
  page === PAGES.SEARCH_PUBLICATIONS
